package com.hzj.beans;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.st
     *
     * @mbggenerated
     */
    private String st;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_type_id
     *
     * @mbggenerated
     */
    private NewsType newsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.browser_count
     *
     * @mbggenerated
     */
    private Integer browserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.photo
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.st
     *
     * @return the value of news.st
     *
     * @mbggenerated
     */
    public String getSt() {
        return st;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.st
     *
     * @param st the value for news.st
     *
     * @mbggenerated
     */
    public void setSt(String st) {
        this.st = st == null ? null : st.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.author
     *
     * @return the value of news.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.author
     *
     * @param author the value for news.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

   

    public NewsType getNewsType() {
		return newsType;
	}

	public void setNewsType(NewsType newsType) {
		this.newsType = newsType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.browser_count
     *
     * @return the value of news.browser_count
     *
     * @mbggenerated
     */
    public Integer getBrowserCount() {
        return browserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.browser_count
     *
     * @param browserCount the value for news.browser_count
     *
     * @mbggenerated
     */
    public void setBrowserCount(Integer browserCount) {
        this.browserCount = browserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.photo
     *
     * @return the value of news.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.photo
     *
     * @param photo the value for news.photo
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}