package com.hzj.beans;

public class NewsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.news_id
     *
     * @mbggenerated
     */
    private News news;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.id
     *
     * @return the value of news_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.id
     *
     * @param id the value for news_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

  

    public News getNews() {
		return news;
	}

	public void setNews(News news) {
		this.news = news;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.info
     *
     * @return the value of news_info.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.info
     *
     * @param info the value for news_info.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}